//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceChess.SquareTimeProcessingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SquareTimeProcessingService.ISquareTimeProcessingService")]
    public interface ISquareTimeProcessingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/Start", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/StartResponse")]
        void Start(string pathFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/Start", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/StartResponse")]
        System.Threading.Tasks.Task StartAsync(string pathFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/Suspend", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/SuspendResponse")]
        void Suspend(bool run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/Suspend", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/SuspendResponse")]
        System.Threading.Tasks.Task SuspendAsync(bool run);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/isFirstLTSecund", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/isFirstLTSecundResponse")]
        bool isFirstLTSecund(byte FirstCase, byte SecundCase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/isFirstLTSecund", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/isFirstLTSecundResponse")]
        System.Threading.Tasks.Task<bool> isFirstLTSecundAsync(byte FirstCase, byte SecundCase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/SetFirstHit", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/SetFirstHitResponse")]
        void SetFirstHit(byte noCase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/SetFirstHit", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/SetFirstHitResponse")]
        System.Threading.Tasks.Task SetFirstHitAsync(byte noCase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/GetFirstHit", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/GetFirstHitResponse")]
        System.DateTime GetFirstHit(byte nocase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/GetFirstHit", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/GetFirstHitResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetFirstHitAsync(byte nocase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/NewGame", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/NewGameResponse")]
        bool NewGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISquareTimeProcessingService/NewGame", ReplyAction="http://tempuri.org/ISquareTimeProcessingService/NewGameResponse")]
        System.Threading.Tasks.Task<bool> NewGameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISquareTimeProcessingServiceChannel : InterfaceChess.SquareTimeProcessingService.ISquareTimeProcessingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SquareTimeProcessingServiceClient : System.ServiceModel.ClientBase<InterfaceChess.SquareTimeProcessingService.ISquareTimeProcessingService>, InterfaceChess.SquareTimeProcessingService.ISquareTimeProcessingService {
        
        public SquareTimeProcessingServiceClient() {
        }
        
        public SquareTimeProcessingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SquareTimeProcessingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SquareTimeProcessingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SquareTimeProcessingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Start(string pathFile) {
            base.Channel.Start(pathFile);
        }
        
        public System.Threading.Tasks.Task StartAsync(string pathFile) {
            return base.Channel.StartAsync(pathFile);
        }
        
        public void Suspend(bool run) {
            base.Channel.Suspend(run);
        }
        
        public System.Threading.Tasks.Task SuspendAsync(bool run) {
            return base.Channel.SuspendAsync(run);
        }
        
        public bool isFirstLTSecund(byte FirstCase, byte SecundCase) {
            return base.Channel.isFirstLTSecund(FirstCase, SecundCase);
        }
        
        public System.Threading.Tasks.Task<bool> isFirstLTSecundAsync(byte FirstCase, byte SecundCase) {
            return base.Channel.isFirstLTSecundAsync(FirstCase, SecundCase);
        }
        
        public void SetFirstHit(byte noCase) {
            base.Channel.SetFirstHit(noCase);
        }
        
        public System.Threading.Tasks.Task SetFirstHitAsync(byte noCase) {
            return base.Channel.SetFirstHitAsync(noCase);
        }
        
        public System.DateTime GetFirstHit(byte nocase) {
            return base.Channel.GetFirstHit(nocase);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetFirstHitAsync(byte nocase) {
            return base.Channel.GetFirstHitAsync(nocase);
        }
        
        public bool NewGame() {
            return base.Channel.NewGame();
        }
        
        public System.Threading.Tasks.Task<bool> NewGameAsync() {
            return base.Channel.NewGameAsync();
        }
    }
}
